version: "3.8"
services: 
  nginx: 
    #container_name: nginx_
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - front-end 

  front-end: 
    #container_name: front_end_api
    image: bryleen1/front-end:latest
    #build: ./front_end_api
    deploy:
      replicas: 3
    depends_on: 
    - truth_api
    - dare_api 
    - merge_api

  truth_api: 
    #container_name: truth_api
    image: bryleen1/truth:latest
    #build: ./truth_api
    deploy:
      replicas: 3


  dare_api:
    #container_name: dare_api
    image: bryleen1/dare:latest
    #build: ./dare_api
    deploy: 
      replicas: 3

  merge_api:
    #container_name: merge_api
    image: bryleen1/merge:latest
    #build: ./merge_api
    deploy: 
      replicas: 3
    