version: "3.8"
services: 
  nginx: 
    container_name: nginx_
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - front-end 

  front-end: 
    container_name: front_end_api
    image: docker.io/bryleen1/front-end-api:latest
    build: ./front_end_api
    depends_on: 
    - truth_api
    - dare_api 
    - merge_api

  truth_api: 
    container_name: truth_api
    image: docker.io/bryleen1/truth-api:latest
    build: ./truth_api
    deploy:
      replicas: 3


  dare_api:
    container_name: dare_api
    image: docker.io/bryleen1/dare-api:latest
    build: ./dare_api
    deploy: 
      replicas: 3

  merge_api:
    container_name: merge_api
    image: docker.io/bryleen1/merge-api:latest
    build: ./merge_api
    deploy: 
      replicas: 3
    